Injeção de Dependência
teaching-labs/avaliacao-3-NatalioJunior pull request #2
Opened 2022-10-26 22:25 UTC by NatalioJunior

As classes dos pacotes Services e Controller passaram a receber dependência via construtor.

2022-10-26 22:30 UTC, NatalioJunior commented
Algumas classes tinham mais de uma dependência (Service e Repository), priorizamos em especificar para cada pacote afim de facilitar os testes. Dessa maneira, as classes Services tendem a depender somente de seus respectivos Repository, enquanto as classes Controller tendem a depender somente de seus Services.

2022-10-27 22:25 UTC, NatalioJunior commented
Sobre Observabilidade e Controlabilidade: A respeito das classes do pacote Controller (OrderedController, ProductController, TableController) e para o pacote Service (Ordered Services, ProductServices e TableServices), decidimos que mudanças não são necessárias, pois os métodos já permitem maneiras de observar o que é retornado e controlar como são manipulados.

Por exemplo: classes do pacote Controller, em sua maioria, retornam respostas das requisições HTTP (OK, BAD REQUEST, etc), já as classes do pacote Service costumam retornar listas de objetos.

2022-10-28 16:40 UTC, mikeiasgabriel commented on src/main/java/br/edu/ufersa/LeMenu/Controller/AuthController.java
>  	@Autowired
O @Autowired é uma anotação que faz injeção de dependências através do container de DI do Spring. Quando definimos o construtor para todas as dependências de um Bean, o container de injeção de dependências consegue resolvê-las mesmo sem a definição desse @Autowired. Por isso, sugiro removê-lo.

Artigo relacionado: https://www.baeldung.com/constructor-injection-in-spring

2022-10-28 16:40 UTC, mikeiasgabriel commented on src/main/java/br/edu/ufersa/LeMenu/Controller/AuthController.java
>  	@Autowired
O mesmo para os outros beans que recebem dependências via construtor.

2022-10-28 16:40 UTC, mikeiasgabriel commented on src/main/java/br/edu/ufersa/LeMenu/Controller/ClerkController.java
>  	private PasswordEncoder encoder;
Essa dependência não é injetada via construtor e também está relacionada com uma biblioteca externa.

Sugiro criar um wrapper (adapter) para isolar essa lógica dentro da sua aplicação, aumentando a estabilidade em relação a mudanças externas no futuro. Por exemplo, caso o contrato dessa biblioteca mude.

2022-10-28 16:41 UTC, mikeiasgabriel commented on src/main/java/br/edu/ufersa/LeMenu/service/ClientServices.java
>  	public List<Client> findAll() {
Sugiro remover métodos que não são usados. Uma codebase menor é mais fácil de manter.

2022-10-28 16:45 UTC, mikeiasgabriel requested changes

2022-10-28 16:45 UTC, mikeiasgabriel commented on src/main/java/br/edu/ufersa/LeMenu/Controller/AuthController.java
>  	@Autowired
O @Autowired é uma anotação que faz injeção de dependências através do container de DI do Spring. Quando definimos o construtor para todas as dependências de um Bean, o container de injeção de dependências consegue resolvê-las mesmo sem a definição desse @Autowired. Por isso, sugiro removê-lo.

Artigo relacionado: baeldung.com/constructor-injection-in-spring

O mesmo para os outros beans que recebem dependências via construtor.

2022-10-28 16:45 UTC, mikeiasgabriel requested changes

2022-10-28 16:45 UTC, mikeiasgabriel commented on src/main/java/br/edu/ufersa/LeMenu/Controller/ClerkController.java
>  	private PasswordEncoder encoder;
Essa dependência não é injetada via construtor e também está relacionada com uma biblioteca externa.

Sugiro criar um wrapper (adapter) para isolar essa lógica dentro da sua aplicação, aumentando a estabilidade em relação a mudanças externas no futuro. Por exemplo, caso o contrato dessa biblioteca mude.

2022-10-28 16:46 UTC, mikeiasgabriel requested changes

2022-10-28 16:46 UTC, mikeiasgabriel commented on src/main/java/br/edu/ufersa/LeMenu/service/ClientServices.java
>  	public List<Client> findAll() {
Sugiro remover métodos que não são usados. Uma codebase menor é mais fácil de manter.

2022-10-28 16:48 UTC, mikeiasgabriel commented
- Também sugiro normalizar os nomes dos pacotes para todo em minusculo, só por questão de padronização. 

Bom trabalho, pessoal!

2022-10-28 22:58 UTC, mikeiasgabriel commented on src/main/java/br/edu/ufersa/LeMenu/Controller/ClerkController.java
> +	final private UserRepository repo;
Acredito que a legibilidade do código pode ser prejudicada quando usamos siglas, códigos ou reduções para atributos ou dependências. 

Sugiro manter sempre nomes significativos e claros do que algo representa no contexto, mesmo que possam parecer redudantes ou grandes. Isso porque no futuro podemos ter mais dificuldade de entender o que a dependência representa no código.

Um exercício que pode ser útil é ler determinada função ou classe e tentar verificar se tudo faz sentido sem ter que voltar nas definições das variáveis de instância.

Nessa classe, poderia ser assim:

```java
	final private UserRepository userRepository;
```

Vocês acham que faz sentido?

2022-10-28 22:58 UTC, mikeiasgabriel commented on src/main/java/br/edu/ufersa/LeMenu/Controller/ClientController.java
> +	final private OrderingTableRepository tbRepos;
Mesma questão de siglas, códigos ou reduções para nomes de variáveis. É uma boa prática manter os nomes claros no contexto em que estão inseridos.

2022-10-28 23:17 UTC, mikeiasgabriel requested changes
Vi que esse pequeno problema de escrita de variáveis existe para outros métodos, sugiro esse ajuste para melhoria de legibilidade.

2022-10-28 23:17 UTC, mikeiasgabriel commented on src/main/java/br/edu/ufersa/LeMenu/Controller/ClerkController.java
> +	final private UserRepository repo;
Acredito que a legibilidade do código pode ser prejudicada quando usamos siglas, códigos ou reduções para atributos ou dependências. 

Sugiro manter sempre nomes significativos e claros do que algo representa no contexto, mesmo que possam parecer redudantes ou grandes. Isso porque no futuro podemos ter mais dificuldade de entender o que a dependência representa no código.

Um exercício que pode ser útil é ler determinada função ou classe e tentar verificar se tudo faz sentido sem ter que voltar nas definições das variáveis de instância.

Nessa classe, poderia ser assim:

```java
	final private UserRepository userRepository;
```

Vocês acham que faz sentido?

2022-10-28 23:17 UTC, mikeiasgabriel commented on src/main/java/br/edu/ufersa/LeMenu/Controller/ClientController.java
> +	final private OrderingTableRepository tbRepos;
Mesma questão de siglas, códigos ou reduções para nomes de variáveis. É uma boa prática manter os nomes claros no contexto em que estão inseridos.

2022-11-07 00:31 UTC, flaviacoelho commented
Código-fonte e revisão estão de acordo com a especificação.

2022-11-10 13:51 UTC, merged